### ISSUE TITLE
Session and ArlulaAPI usage

### ISSUE THREAD

**Issue by markmnl** [Arlula/python-core-sdk#8]
Should a new Session and ArlulaAPI be created every call, or can I keep a session around indefinitely, same for instance of ArlulaAPI ?

**Comment by Maldris** [comment]
Both Session and the connection client (`ArlulaAPI`) are designed to be used as long lived objects that you keep around and use to make subsequent calls (they are treated as read only providers).

Keeping the session/client around also makes it simpler to have two or more accounts with different sharing teams or access permissions in use in your code at a time

In saying that, there is no reason they can't be used as ephemeral objects and re-initialized as needed, the main trade-offs for this are:
1. You will need to keep credentials stored somewhere accessible in your code, to reinitialize a Session object each time you need to use it.
2. when a session is initialized it verifies its credentials and configuration with a call to the test endpoint synchronously, which adds a delay which could be avoided with a long lived client

Hope that helps, we'll try to include some of these details in the readme when the next update goes live to clear things up

**Comment by martejj** [comment]
Forgot to close after adding explanation to the README and wiki.
